theme = "term16_dark" # heisenberg, merionette, peachpuff, vim_dark_high_contrast


[editor]
# scrolloff = 9
scroll-lines = 1
cursorline = true
auto-save = false
completion-trigger-len = 1
true-color = true
auto-pairs = true
# rulers = [120]
idle-timeout = 50
line-number = "relative"
bufferline = "multiple"
color-modes = true
end-of-line-diagnostics = "hint"
mouse = false
middle-click-paste = false

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.indent-guides]
render = true
character = "·" # Some characters that work well: " ▏", " ┆ ", " ┊ ", " ⸽"
skip-levels = 1

[editor.lsp]
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator", "separator", "version-control"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
ignore = false
git-ignore = false

[editor.soft-wrap]
enable = false

[keys.insert]
f = { j = "normal_mode" } # Maps "fj" to exit insert mode
j = { f = "normal_mode" } # Maps "fj" to exit insert mode

[keys.normal]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
# "y" = "primary-clipboard-yank"
# "Y" = "primary-clipboard-yank-join"
# "P" = "primary-clipboard-paste-before"
# "p" = "primary-clipboard-paste-after"

[keys.normal.space]
"x" = ":write-quit"
"q" = ":quit"
"W" = ":write"

[keys.normal.space.l]
a = ":set line-number absolute" 
r = ":set line-number relative" 
n = ":set line-number none" 

[keys.select]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
